Run the following code cell to import the NumPy module

In [0]:
import numpy as np

**Call np.array to create a NumPy matrix**

In [0]:
one_dim_array = np.array([1,2.2,3.3,4.4])
print(one_dim_array)

[1.  2.2 3.3 4.4]


In [0]:
two_dim_array = np.array([[1, 2], [2, 3], [3, 4]])
print(two_dim_array)

[[1 2]
 [2 3]
 [3 4]]


Populate Array With Sequence Numbers

In [0]:
seq_of_integers = np.arange(1, 11)
print(seq_of_integers)

[ 1  2  3  4  5  6  7  8  9 10]


populate Array with Random Numbers


In [0]:
random_int_between_10_and_100 = np.random.randint(low=10, high=101, size=(6))
print(random_int_between_10_and_100)

[62 56 86 17 48 96]


populate array with random floating values


In [0]:
ran_floats_between_0_and_1 = np.random.random([6])
print(ran_floats_between_0_and_1) 

[0.46275136 0.53384862 0.81310869 0.73206752 0.46178785 0.25729944]


Mathemathical operations on NumPy

In [0]:
ran_floats_between_2_and_3 = ran_floats_between_0_and_1 + 2.0
print(ran_floats_between_2_and_3)

[2.46275136 2.53384862 2.81310869 2.73206752 2.46178785 2.25729944]


Create a dataset


In [0]:
feature = np.arange(6, 21)
print(feature)
label = (feature * 3) + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


Add Noise to dataset

In [0]:
noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise 
print(label)

[ 1.70442349  1.6179547   0.36230522  0.96523047  0.69094787  1.98998436
  1.83300788 -1.73419284  1.15876359 -0.21568172 -1.75845457  0.05640207
 -0.07455456  0.63926597 -0.53115099]
[23.70442349 26.6179547  28.36230522 31.96523047 34.69094787 38.98998436
 41.83300788 41.26580716 47.15876359 48.78431828 50.24154543 55.05640207
 57.92544544 61.63926597 63.46884901]


**Pandas**

In [0]:
import pandas as pd

In [0]:
# Create and populate a 5x2 NumPy array.
my_data = np.array([[0, 3], [10, 7], [20, 9], [30, 14], [40, 15]])

# Create a Python list that holds the names of the two columns.
my_column_names = ['temperature', 'activity']

# Create a DataFrame.
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names)

# Print the entire DataFrame
print(my_dataframe)

   temperature  activity
0            0         3
1           10         7
2           20         9
3           30        14
4           40        15


Adding column to Dataframe

In [0]:
# Create a new column named adjusted.
my_dataframe["adjusted"] = my_dataframe["activity"] + 2

# Print the entire DataFrame
print(my_dataframe)

   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11
3           30        14        16
4           40        15        17


Subset of dataframe

In [0]:
print("Rows #0, #1, and #2:")
print(my_dataframe.head(3), '\n')

print("Row #2:")
print(my_dataframe.iloc[[2]], '\n')

print("Rows #1, #2, and #3:")
print(my_dataframe[1:4], '\n')

print("Column 'temperature':")
print(my_dataframe['temperature'])

Rows #0, #1, and #2:
   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11 

Row #2:
   temperature  activity  adjusted
2           20         9        11 

Rows #1, #2, and #3:
   temperature  activity  adjusted
1           10         7         9
2           20         9        11
3           30        14        16 

Column 'temperature':
0     0
1    10
2    20
3    30
4    40
Name: temperature, dtype: int64
